<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="Content-Style-Type" content="text/css" /><meta name="generator" content="Aspose.Words for .NET 19.9" /><title></title></head><body><div><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">Answer: The method at the top of the stack throws an exception if it is not caught.</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">It moves to the next method and goes on like this until caught. Example:</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">public class Sum()</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">{</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">public static void main(String args[])</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">{</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">addition()</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">public void addition()</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">{</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">add();</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">}</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">The stack of the above code is:</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">add()</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">addition()</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">main()</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">If an exception occurred in the add() method is not caught, then it moves to the</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">method addition(). It is then moved to the main() method, where the flow of</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri">execution stops. It is called Exception Propagation.</span></p><p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt"><span style="font-family:Calibri; -aw-import:ignore">&#xa0;</span></p></div></body></html>